function figure1=choicePatternFig(cdata1, cdata2, X1, Y1)
%CREATEFIGURE(CDATA1, CDATA2, X1, Y1)
%  CDATA1:  image cdata
%  CDATA2:  image cdata
%  X1:  scatter x
%  Y1:  scatter y

%  Auto-generated by MATLAB on 11-Aug-2017 16:40:01

% Create figure
figure1=figure;
set(gcf, 'Position', get(0, 'Screensize'));

% Create axes
axes1 = axes('Parent',figure1,'Position',[0.102707348517404 0.625670277759435 0.230661796304254 0.247778835547925]);
hold(axes1,'on');

% Create image
image(cdata1,'Parent',axes1);

box(axes1,'on');
axis(axes1,'tight');
axis(axes1,'ij');
% Set the remaining axes properties
set(axes1,'DataAspectRatio',[1 1 1],'Layer','top','PlotBoxAspectRatio',[814.5 377.5 1],'TickDir','out');
% Create axes
axes2 = axes('Parent',figure1,'Position',[0.358998732572875 0.128351585084659 0.466413181242075 0.896775104104531]);
axis off
hold(axes2,'on');

% Create image
image(cdata2,'Parent',axes2,'CDataMapping','scaled');

% Create scatter
scatter(X1,Y1,'Parent',axes2,'MarkerFaceColor',[1 1 0],'MarkerEdgeColor',[1 1 0],'Marker','x');

box(axes2,'on');
axis(axes2,'ij');
% Set the remaining axes properties
set(axes2,'DataAspectRatio',[1 1 1],'Layer','top','PlotBoxAspectRatio',[685.381818181818 659.172 0.299623636363636]);
% Create textbox
annotation(figure1,'textbox',[0.538656527249677 0.891736485640757 0.126742715189917 0.046030406251147],...
    'String',{'Calibration Image'},...
    'LineStyle','none',...
    'FontSize',20,...
    'FitBoxToText','off');

% Create textbox
annotation(figure1,'textbox',[0.174664656502914 0.886334108823282 0.0908322791837671 0.0392736493332966],...
    'String',{'Choice Pattern'},...
    'LineStyle','none',...
    'FontSize',16,...
    'FitBoxToText','off');

% Create textbox
annotation(figure1,'textbox',[0.0971646923597974 0.31604161864937 0.145249088678446 0.245527389993303],...
    'String',{'Please choose the dots on the calibration','pattern in the order indicated in the above','diagram','','It is imperical that the points 1, 2, 3 and 4 are','resolved (detected by the image','processor and marked by cross in the figure','on the right). If that is not the case new','calibration image needs to be supplied.'},...
    'LineStyle','none',...
    'FitBoxToText','off');

