function invReprojErrFig(X1, Y1, U1, V1, tri, FaceVertexCData1, data1)
%CREATEFIGURE(X1, Y1, U1, V1, X2, Y2, S1, VERTICES1, FACES1, FACEVERTEXCDATA1, DATA1)
%  X1:  quiver x
%  Y1:  quiver y
%  U1:  quiver u
%  V1:  quiver v
%  VERTICES1:  patch vertices
%  FACES1:  patch faces
%  FACEVERTEXCDATA1:  patch facevertexcdata
%  DATA1:  histogram data

%  Auto-generated by MATLAB on 16-Aug-2017 14:45:49

% Create figure
figure1 = figure;
set(gcf, 'Position', get(0, 'Screensize'));

% Create axes
axes1 = axes('Parent',figure1,'Position',[0.51708984375 0.41025147549397 0.36083984375 0.474082627662304]);
hold(axes1,'on');

% Create quiver
quiver(X1,Y1,U1,V1,'DisplayName','Inverse Reprojection Error Vector','Parent',axes1,'LineWidth',0.5,'AutoScaleFactor',5);

% Create xlabel
xlabel('X, mm','FontSize',11);

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[-50 200]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[-150 50]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'DataAspectRatio',[1 1 1],'PlotBoxAspectRatio',[3300 2200 1]);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Position',[0.7336914060032 0.827952346167516 0.107128908326849 0.0376599912604121]);

% Create axes
axes2 = axes('Parent',figure1,'Position',[0.08740234375 0.41025147549397 0.36083984375 0.474082627662304]);
hold(axes2,'on');

% Create patch
trisurf(tri, X1,Y1, FaceVertexCData1,'LineStyle','none');

% Create ylabel
ylabel('Y, mm');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes2,[-50 200]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes2,[-150 50]);
grid(axes2,'on');
% Set the remaining axes properties
set(axes2,'DataAspectRatio',[1 1 1],'PlotBoxAspectRatio',[3300 2200 1]);
% Create axes
axes3 = axes('Parent',figure1,'Position',[0.36083984375 0.0952655889145479 0.234375 0.211701308699001]);
hold(axes3,'on');

% Create histogram
histogram(data1,'BinMethod','auto');

% Create xlabel
xlabel('Inverse Reprojection Error, mm','LineWidth',4,'FontSize',14);

% Create title
title('Histogram of Inverse Reprojection Error Magnitude','Units','pixels','FontSize',12);

% Create ylabel
ylabel('Count','Units','pixels','LineWidth',4,'FontSize',14);

box(axes3,'on');
% Create textbox
annotation(figure1,'textbox',[0.355859375 0.888687643911917 0.251953125 0.0577367205542726],...
    'String','Summary of Inverse Reprojection Error',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',20,...
    'FitBoxToText','off');

