function figure1=createFigMasking(cdata1)
%CREATEFIGURE(CDATA1)
%  CDATA1:  image cdata

%  Auto-generated by MATLAB on 19-Oct-2017 18:52:04

% Create figure
figure1=figure;
set(gcf, 'Position', get(0, 'Screensize'));

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create image
image(cdata1,'Parent',axes1,'CDataMapping','scaled');

box(axes1,'on');
axis(axes1,'tight');
axis(axes1,'ij');
% Set the remaining axes properties
set(axes1,'DataAspectRatio',[1 1 1],'Layer','top');
% Create textbox
annotation(figure1,'textbox',...
    [0.337109375 0.938335046248714 0.3640625 0.0509013360739977],...
    'String','Choose vertices of the polygonal mask (ENTER when done)',...
    'LineWidth',20,...
    'LineStyle','none',...
    'FontSize',20,...
    'FitBoxToText','off');

